# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/user/yswang/task/wekws/cpp/audio/wekws2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/user/yswang/task/wekws/cpp/audio/wekws2/build_linux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/user/yswang/task/wekws/cpp/audio/wekws2/build_linux/CMakeFiles /data/user/yswang/task/wekws/cpp/audio/wekws2/build_linux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/user/yswang/task/wekws/cpp/audio/wekws2/build_linux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mylib

# Build rule for target.
mylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mylib
.PHONY : mylib

# fast build rule for target.
mylib/fast:
	$(MAKE) $(MAKESILENT) -f src/mylib/CMakeFiles/mylib.dir/build.make src/mylib/CMakeFiles/mylib.dir/build
.PHONY : mylib/fast

#=============================================================================
# Target rules for targets named mylib_so

# Build rule for target.
mylib_so: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mylib_so
.PHONY : mylib_so

# fast build rule for target.
mylib_so/fast:
	$(MAKE) $(MAKESILENT) -f src/mylib/CMakeFiles/mylib_so.dir/build.make src/mylib/CMakeFiles/mylib_so.dir/build
.PHONY : mylib_so/fast

#=============================================================================
# Target rules for targets named mylib_test

# Build rule for target.
mylib_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mylib_test
.PHONY : mylib_test

# fast build rule for target.
mylib_test/fast:
	$(MAKE) $(MAKESILENT) -f src/mylib_test/CMakeFiles/mylib_test.dir/build.make src/mylib_test/CMakeFiles/mylib_test.dir/build
.PHONY : mylib_test/fast

#=============================================================================
# Target rules for targets named wekws

# Build rule for target.
wekws: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wekws
.PHONY : wekws

# fast build rule for target.
wekws/fast:
	$(MAKE) $(MAKESILENT) -f src/wekws/CMakeFiles/wekws.dir/build.make src/wekws/CMakeFiles/wekws.dir/build
.PHONY : wekws/fast

#=============================================================================
# Target rules for targets named wekws_so

# Build rule for target.
wekws_so: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wekws_so
.PHONY : wekws_so

# fast build rule for target.
wekws_so/fast:
	$(MAKE) $(MAKESILENT) -f src/wekws/CMakeFiles/wekws_so.dir/build.make src/wekws/CMakeFiles/wekws_so.dir/build
.PHONY : wekws_so/fast

#=============================================================================
# Target rules for targets named wekws_test

# Build rule for target.
wekws_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wekws_test
.PHONY : wekws_test

# fast build rule for target.
wekws_test/fast:
	$(MAKE) $(MAKESILENT) -f src/wekws_test/CMakeFiles/wekws_test.dir/build.make src/wekws_test/CMakeFiles/wekws_test.dir/build
.PHONY : wekws_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mylib"
	@echo "... mylib_so"
	@echo "... mylib_test"
	@echo "... wekws"
	@echo "... wekws_so"
	@echo "... wekws_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

